name: Build and Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Choose the deployment environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - uat
          - prod
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/build.yaml
      - .github/actions/setupnode/action.yaml
      - .github/actions/setupnode/package.json
      - .github/actions/setupnode/package-lock.json
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Node.js setup action
        uses: ./.github/actions/setupnode

      - name: Build the project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist  # adjust this to your output folder (e.g., web-build, build, etc.)

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: site

      - name: Checkout repo (for env files)
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
